### ISSUE TITLE
Fastmap not installing for 1.1.1 

### ISSUE THREAD

**Issue by abiboakye** [r-lib/fastmap#35]
Hello, 

I am getting same error message with 3.5.1 can they confirm fastmap_1.1.1 works for R version 3.5.1. This is a dependency for sparklyr 1.1.0 to be able to install.

That is the error when i try to do the installation: Any help?
usr/local/lib/R/etc/Makeconf:168: recipe for target 'fastmap.o' failed
make: *** [fastmap.o] Error 1
ERROR: compilation failed for package ‘fastmap’
* removing ‘/home/cdsw/R/fastmap’
Error: Failed to install 'unknown package' from URL:

**Comment by wch** [comment]
This is probably the same issue as https://github.com/rstudio/httpuv/issues/360. I've copied and pasted the comment from @gadenbuie in that issue:

*****

I think you're running into an issue caused by changes in CRAN policy around packages that contain C++ code. If you're interested in the backstory, there's [an article on the tidyverse blog that explains the change](https://www.tidyverse.org/blog/2023/03/cran-checks-compiled-code/#how-to-fix-it).

The [fix as described there](https://www.tidyverse.org/blog/2023/03/cran-checks-compiled-code/#how-to-fix-it) is that for R <= 3.5, you may need to make a small change in your `~/.R/Makevars` file to add the following line:

```
CXX_STD=CXX11
```

Please try this and let us know how it goes.
